_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
alpha_max:
    value: 0.001
alpha_min:
    value: 1e-08
batch_size:
    value: 32
dropout_rate:
    value: 0
eval_batch_size:
    value: 2048
lr:
    value: 0.001
model_params:
    value: 11175690
momentum:
    value: 0.9
n_epochs:
    value: 100
nesterov:
    value: true
num_attackers:
    value: 1
num_eval_workers:
    value: 4
num_quantiles:
    value: 10
num_workers:
    value: 2
optimizer:
    value: adam
resnet_channel_reduce:
    value: 1
scheduler:
    value: cosine
target_alpha:
    value: 0.001
weight_decay:
    value: 0.0001
